### ISSUE TITLE
Missing dependency com.github.multiformats:java-multibase:v1.1.0

### ISSUE THREAD

**Issue by kosmovyspa** [danubetech/verifiable-credentials-java#38]
Project can't be built because Gradle can't find `com.github.multiformats:java-multibase:v1.1.0` dependency. And I can't find it manually as well. It miss both in maven central and in [repo.danubetech.com](https://repo.danubetech.com/#browse/browse:maven-public).

FYI: it is possible to overcome this issue as sources of the `java-multibase` are available on GitHub [here](https://github.com/multiformats/java-multibase/releases/tag/v1.1.0).

**Comment by kosmovyspa** [comment]
FYI: I see that mavenCentral refers to the https://repository.mulesoft.org/nexus/content/repositories/public/com/github/multiformats/java-multibase/, but this repo doesn't contain any version of the `java-multibase`.

**Comment by fabrii** [comment]
Try one of these

```
<repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>danubetech-maven-releases</id>
            <url>https://repo.danubetech.com/repository/maven-releases/</url>
        </repository>
```

**Comment by kosmovyspa** [comment]
I think the issue can be closed, as Jitpack fixes it.
